<?php get_header(); ?>
<div class="hd-home">
<section class="hd-hero" style="--hero-image:url('<?php echo esc_url(hd_hero_image_url(16)); ?>')"><div class="hd-wrap hero-content"><span class="eyebrow">Toronto &amp; the GTA</span><h1>Balloon Decoration That Brings Toronto Celebrations to Life</h1><p>Custom balloon decoration in Toronto and the GTA for birthdays, weddings, baby showers, corporate events, and private celebrations.</p><a class="hd-btn" href="#contact">Start Planning Your Celebration <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></div></section>

<section id="about"><div class="hd-wrap hd-split"><div class="split-copy"><span class="eyebrow">Made for your moment</span><h2>Custom Balloon Decor for Every Celebration</h2><p>Every event is different, so our balloon decor is planned around your occasion, venue, colour palette, and overall style. We create soft and elegant setups, bright birthday themes, luxury balloon garlands, branded corporate displays, romantic engagement decor, and fun party installations.</p><ul class="check-grid"><li>Balloon garlands &amp; arches</li><li>Backdrops &amp; photo zones</li><li>Ceiling balloon decor</li><li>Entrance displays</li><li>Balloon &amp; flower decor</li><li>Themed party decor</li><li>Rental setups</li><li>Bouncy castle rentals</li></ul><p>Happy Day Toronto provides event decor services across Toronto and the GTA.</p></div><figure class="hd-about-photo"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/about-happy-day-toronto.jpeg'); ?>" width="1000" height="1333" loading="eager" fetchpriority="high" decoding="async" alt="Happy Day Toronto decorator preparing custom balloons for a colourful celebration"></figure></div></section>

<section class="soft" id="services"><div class="hd-wrap"><div class="section-head center"><span class="eyebrow">What we create</span><h2>Balloon Decoration Services</h2><p>Explore custom balloon decoration for every event, venue and party style.</p></div><div class="services-grid">
<?php $services=[
['Birthday Balloon Decorations','Colourful balloon garlands, arches, backdrops, number displays and themed decor for kids, teens and adults.','/services/balloons-for-birthdays/'],
['Wedding Balloon Decor','Elegant ceremony, reception, entrance, dessert-table and photo-backdrop installations.','/services/wedding-balloons/'],
['Corporate Event Balloons','Polished branded decor for launches, office parties, openings, trade shows and celebrations.','/services/corporate-event-balloons/'],
['Baby Shower Balloons','Soft colours, themed garlands, elegant arches and photo-ready display areas.','/services/baby-shower-balloons/'],
['Bridal Shower Balloons','Elegant bride-to-be backdrops, floral garlands, arches and celebration photo areas.','/services/bridal-shower-balloons/'],
['Balloon Arches & Garlands','Custom statement pieces for entrances, dessert tables, photo zones and stages.','/services/balloon-arch-garland/'],
['Balloon & Flower Decoration','A refined mix of organic balloon arrangements and florals for luxury event setups.','/services/balloon-and-flower-decoration/'],
['Anniversary Balloon Decoration','Romantic balloon setups for intimate dinners, milestone celebrations and surprise parties.','/services/anniversary-balloons/'],
['Baptism Balloons','Soft, elegant decor for family gatherings, churches, banquet halls and restaurants.','/services/baptism-balloons/'],
['Christmas Balloons','Festive custom decorations for holiday parties, offices, families and seasonal photos.','/services/christmas-balloons/'],
['Valentine’s Day Balloons','Romantic decor for private events, proposals, restaurants and brand displays.','/services/valentines-day-balloons/'],
['Bar Mitzvah Balloons','Themed garlands, arches, entrances and backdrops for an unforgettable celebration.','/services/bar-mitzvah-balloons/'],
['Backdrop Rental','Versatile backdrops for parties, weddings, showers, corporate events and photoshoots.','/services/backdrop-rental/'],
['Balloon Ceiling Decor','Dramatic overhead installations for birthdays, schools, corporate and holiday events.','/services/balloon-ceiling-decor/'],
['Graduation Balloons','School colours, number displays, backdrops and photo-ready graduation decor.','/services/graduation-balloons/'],
['Engagement Balloons','Elegant installations for proposals, engagement parties and romantic photo areas.','/services/engagement-balloons/'],
['Halloween Balloons','Spooky, playful or stylish themed garlands, arches and party backdrops.','/services/halloween-balloons/']]; foreach($services as $s):
$service_slug=basename(trim(parse_url($s[2],PHP_URL_PATH),'/'));
$service_file=get_template_directory().'/inc/services/'.$service_slug.'.php';
$service_image=0;
if(file_exists($service_file)){$service_card_data=require $service_file;$service_image=(int)($service_card_data['hero_image']??0);}
?>
<article class="service-card"><a class="card-visual" href="<?php echo esc_url(hd_local_url($s[2])); ?>" aria-label="<?php echo esc_attr($s[0]); ?>"><?php if($service_image): echo wp_get_attachment_image($service_image,'large',false,['loading'=>'lazy']); endif; ?><span class="service-card-glow" aria-hidden="true"></span></a><div class="card-body"><h3><a href="<?php echo esc_url(hd_local_url($s[2])); ?>"><?php echo esc_html($s[0]); ?></a></h3><p><?php echo esc_html($s[1]); ?></p><a class="text-link" href="<?php echo esc_url(hd_local_url($s[2])); ?>"><span>Explore service</span><i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></div></article><?php endforeach; ?>
</div></div></section>

<?php get_template_part('template-parts/instagram-section'); ?>

<div class="gta-section-wave" aria-hidden="true"><svg viewBox="0 0 1440 58" preserveAspectRatio="none" fill="#f2f5fb"><path fill="#f2f5fb" d="M0 58V38C360 8 1080 8 1440 38V58Z"></path></svg></div>
<section class="gta-events-section"><div class="hd-wrap hd-split"><figure class="hd-gta-photo"><?php echo wp_get_attachment_image(18,'large',false,['loading'=>'lazy']); ?></figure><div class="split-copy"><span class="eyebrow">Local event specialists</span><h2>Balloon Decorations for Toronto &amp; GTA Events</h2><p>We work with homes, condos, restaurants, banquet halls, event venues, offices, retail spaces, schools, and outdoor party locations.</p><ul class="check-grid"><li>Birthdays &amp; milestones</li><li>Weddings &amp; engagements</li><li>Baby &amp; bridal showers</li><li>Corporate events</li><li>Graduation parties</li><li>Seasonal celebrations</li></ul><p>If you need balloon decorations in Toronto, balloon decor near you, or a balloon decorator for an upcoming event, our team can help plan a setup that fits your space and style.</p><a class="hd-btn" href="#contact">Get a Free Quote <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></div></div></section>

<section class="band service-marquee" aria-label="Balloon decoration services"><div class="service-marquee-track"><div class="service-marquee-group"><?php foreach($services as $s): ?><a href="<?php echo esc_url(hd_local_url($s[2])); ?>"><i class="fa-solid fa-sparkles" aria-hidden="true"></i><?php echo esc_html($s[0]); ?></a><?php endforeach; ?></div><div class="service-marquee-group" aria-hidden="true"><?php foreach($services as $s): ?><a tabindex="-1" href="<?php echo esc_url(hd_local_url($s[2])); ?>"><i class="fa-solid fa-sparkles" aria-hidden="true"></i><?php echo esc_html($s[0]); ?></a><?php endforeach; ?></div></div></section>

<section class="why-section" id="why-choose"><div class="hd-wrap why-grid"><div class="split-copy"><h2>Why Choose Happy Day Toronto?</h2><p class="why-lead">Choosing the right balloon decorator can make a big difference in how your event looks and feels. Happy Day Toronto focuses on clean design, reliable setup, and decor that looks great in person and in photos.</p><p class="list-intro"><strong>Clients choose us for:</strong></p><ul class="check-grid"><li>Custom event decor</li><li>Colour and theme matching</li><li>Arches, garlands, and backdrops</li><li>Small and large events</li><li>Toronto and GTA service</li><li>Planning-to-setup support</li></ul><p class="why-closing"><span>We help you create a polished event look without making the process complicated.</span></p></div><figure class="why-photo"><video autoplay muted loop playsinline preload="metadata" poster="<?php echo esc_url(get_template_directory_uri().'/assets/images/why-choose-happy-day-toronto-poster.jpg'); ?>" aria-label="Happy Day Toronto custom balloon decoration"><source src="<?php echo esc_url(get_template_directory_uri().'/assets/videos/why-choose-happy-day-toronto.mp4'); ?>" type="video/mp4"></video></figure></div></section>

<section class="google-reviews-section"><div class="hd-wrap"><?php echo do_shortcode('[trustindex no-registration=google]'); ?></div></section>

<section class="soft"><div class="hd-wrap"><div class="section-head"><span class="eyebrow">Simple from start to finish</span><h2>How Our Balloon Decoration Process Works</h2></div><div class="process-grid"><div class="step"><b>01.</b><h3>Share Your Event Details</h3><p>Tell us the date, location, occasion, colours and inspiration.</p></div><div class="step"><b>02.</b><h3>Choose Your Setup</h3><p>We recommend garlands, arches, backdrops or a full custom installation.</p></div><div class="step"><b>03.</b><h3>We Prepare the Decor</h3><p>Our team plans the design, materials, colours and installation.</p></div><div class="step"><b>04.</b><h3>We Set Everything Up</h3><p>We install your decor before guests arrive, ready for celebration.</p></div></div></div></section>

<section id="contact"><div class="hd-wrap quote-box"><div class="quote-copy"><span class="eyebrow">Let’s celebrate</span><h2>Book Balloon Decoration</h2><p>Ready to plan your event? Tell us about your date, location and ideas. We’ll get back to you with details shortly.</p><p class="contact-list"><a href="tel:+16475275505"><i class="fa-solid fa-phone" aria-hidden="true"></i><span>647-527-5505</span></a><a href="mailto:happydaytorontoballoons@gmail.com"><i class="fa-solid fa-envelope" aria-hidden="true"></i><span>happydaytorontoballoons@gmail.com</span></a></p></div><div class="quote-form hd-cf7-card"><?php hd_render_quote_form(); ?></div></div></section>

<section class="soft home-faq-section"><div class="hd-wrap"><div class="section-head"><span class="eyebrow">Helpful details</span><h2>Frequently Asked Questions</h2><p>Find quick answers about balloon decor, booking, event types and setup across Toronto and the GTA.</p></div><div class="faq-list">
<?php $faqs=[
['What should I include when requesting a balloon decoration recommendation?','Send the event date, full location, occasion, guest count, start time, earliest venue access, and a photo or measurement of the intended setup area. Include your preferred colours, inspiration images, approximate budget range, and whether you need a backdrop, signage, flowers, installation, or removal. These details help Happy Day Toronto recommend a realistic design for your space instead of estimating from a reference photo alone.'],
['How do I know whether my event needs one focal display or decor throughout the room?','Begin with the places guests will see and photograph most often. For many celebrations, one well-scaled entrance, dessert-table, stage, or photo feature creates more impact than several small decorations. Larger venues or events with distinct zones may benefit from a main installation plus coordinated accents. We consider room size, guest flow, tables, lighting, camera angles, and budget before recommending how widely the decor should be distributed.'],
['Which locations does Happy Day Toronto serve across the GTA?','Happy Day Toronto works in Toronto and communities across the Greater Toronto Area, subject to date, travel, and venue availability. Installations may take place in homes, condo party rooms, restaurants, banquet halls, offices, retail spaces, schools, community venues, and approved outdoor locations. Send the complete address when enquiring because travel time, parking, loading access, elevators, and local venue rules can affect scheduling and the quote.'],
['What happens after I submit a balloon decor enquiry?','We review the date, location, event type, setup area, and design direction, then follow up about availability and any missing details. Once the scope is clear, the proposed decor, included rentals, installation requirements, and pricing can be confirmed. Custom colours, wording, and layout should be approved before production. Final access instructions and a reachable day-of contact help the installation stay aligned with your event schedule.'],
['Can a balloon design be adapted to strict venue rules or limited setup time?','Often yes. Freestanding structures, compact installations, or a simplified layout may work when walls cannot be used or access is short. However, the venue must confirm attachment restrictions, loading procedures, elevator reservations, ceiling rules, emergency clearances, and removal times. Share those requirements before approving the design. If the original idea is not practical for the room or schedule, we can recommend a safer and more efficient alternative.'],
['How are balloon colours and the final design approved?','We use your invitation, brand guide, mood board, fabric reference, or inspiration photographs to build a coordinated palette and layout. Balloon material reflects light differently from screens, paper, and fabric, so an exact colour match cannot always be guaranteed. The final direction should confirm the main colours, scale, placement, personalization, and included decorative elements. Venue lighting and photographs of the actual space help make those choices more accurate.'],
['What should I consider before choosing an outdoor balloon installation?','Outdoor balloons are affected by wind, direct sunlight, heat, cold, rain, ground conditions, and public access. These factors can change their colour, size, movement, stability, and lifespan. Share photos of the exact location, available shade, installation surface, and event duration. A protected indoor or sheltered backup is strongly recommended, and the design or setup time may need to change if conditions are unsuitable or unsafe.'],
['Are delivery, installation, rentals, and removal automatically included?','Inclusions depend on the specific proposal. A custom setup may involve delivery, on-site installation, balloon materials, structural supports, backdrop or sign rentals, personalization, travel, and scheduled removal, but these should never be assumed from an inspiration image. Review the written quote to see what is included, what remains rented, the access window, and who is responsible after the event. Ask for removal in advance if the venue requires same-day teardown.']
]; foreach($faqs as $i=>$f): ?><details <?php echo $i===0?'open':''; ?>><summary><?php echo esc_html($f[0]); ?></summary><p><?php echo esc_html($f[1]); ?></p></details><?php endforeach; ?>
</div></div><?php
$home_faq_schema=[];
foreach($faqs as $faq){
  $home_faq_schema[]=['@type'=>'Question','name'=>wp_strip_all_tags($faq[0]),'acceptedAnswer'=>['@type'=>'Answer','text'=>wp_strip_all_tags($faq[1])]];
}
?><script type="application/ld+json"><?php echo wp_json_encode(['@context'=>'https://schema.org','@type'=>'FAQPage','mainEntity'=>$home_faq_schema],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE); ?></script></section>
</div><?php get_footer(); ?>
