<?php get_header(); ?>
<div class="about-page">
  <section class="about-intro"><div class="hd-wrap about-split"><div class="about-copy"><h1>About Happy Day Toronto</h1><p class="about-lead">Happy Day Toronto is a local event decor company creating custom balloon decoration in Toronto and across the Greater Toronto Area. We help families, couples, businesses, and event planners bring their celebrations to life with balloon setups that feel beautiful, personal, and ready for photos.</p><p>Our work is made for birthdays, weddings, baby showers, bridal showers, corporate events, baptisms, graduations, engagements, seasonal parties, and private celebrations. From a simple balloon garland to a full backdrop setup, we design decor around your event style, colours, venue, and the moment you want to create.</p></div><figure class="about-main-photo"><img src="<?php echo esc_url(get_template_directory_uri().'/assets/images/about-happy-day-toronto.jpeg'); ?>" width="1000" height="1333" loading="eager" fetchpriority="high" decoding="async" alt="Happy Day Toronto event decorator painting balloons for a custom celebration"></figure></div></section>

  <section class="about-event"><div class="hd-wrap about-split reverse"><figure class="about-event-photo"><?php echo wp_get_attachment_image(18,'large',false,['loading'=>'lazy']); ?></figure><div class="about-copy"><h2>Event Decor Designed Around Your Celebration</h2><p>Every event has its own mood. Some celebrations need soft and elegant balloon decor. Others need bright colours, playful details, branded displays, or a dramatic photo area. That is why we do not use one fixed style for every setup.</p><p>Happy Day Toronto creates balloon decorations that match the occasion, the space, and the people celebrating. We can help with intimate home parties, restaurant events, condo party rooms, banquet halls, offices, schools, retail spaces, and larger event venues across Toronto and the GTA.</p><p>If you are planning a birthday, explore our <a href="<?php echo esc_url(hd_local_url('services/balloons-for-birthdays')); ?>">birthday balloon decorations</a>. For weddings and romantic celebrations, visit our <a href="<?php echo esc_url(hd_local_url('services/wedding-balloons')); ?>">wedding balloon decor</a> and <a href="<?php echo esc_url(hd_local_url('services/engagement-balloons')); ?>">engagement balloon decoration</a> pages.</p></div></div></section>

  <section class="about-create"><div class="hd-wrap"><div class="about-section-head"><h2>What We Create</h2><p>Our decor can be simple, detailed, colourful, elegant, seasonal, or fully customized. Popular options include balloon garlands, balloon arches, balloon backdrops, ceiling balloon decor, themed party setups, event backdrops, and balloon and flower decoration.</p><p>We also offer specific decor services for different event needs:</p></div><div class="about-service-list">
    <a href="<?php echo esc_url(home_url('/services/balloon-arch-garland/')); ?>"><strong>Balloon arch and garland setups</strong><span>Entrances, dessert tables, and photo zones</span><i class="fa-solid fa-arrow-right"></i></a>
    <a href="<?php echo esc_url(home_url('/services/backdrop-rental/')); ?>"><strong>Backdrop rental</strong><span>Birthdays, weddings, showers, photoshoots, and branded events</span><i class="fa-solid fa-arrow-right"></i></a>
    <a href="<?php echo esc_url(home_url('/services/balloon-ceiling-decor/')); ?>"><strong>Balloon ceiling decor</strong><span>Indoor parties and dramatic room styling</span><i class="fa-solid fa-arrow-right"></i></a>
    <a href="<?php echo esc_url(home_url('/services/balloon-and-flower-decoration/')); ?>"><strong>Balloon and flower decoration</strong><span>Softer, more elegant event designs</span><i class="fa-solid fa-arrow-right"></i></a>
    <a href="<?php echo esc_url(home_url('/services/bouncy-castle-rental/')); ?>"><strong>Bouncy castle rental</strong><span>Kids’ parties and family events</span><i class="fa-solid fa-arrow-right"></i></a>
  </div><p class="about-note">Each setup is planned with the event location, installation space, colours, timing, and celebration type in mind.</p></div></section>

  <section class="about-moments"><div class="hd-wrap"><div class="about-section-head"><h2>Balloon Decoration for Life’s Special Moments</h2><p>Happy Day Toronto works with many types of celebrations. Some clients come to us for a first birthday or milestone birthday. Others need a baby shower backdrop, a bridal shower balloon garland, a corporate event display, or seasonal balloon decor for a holiday party.</p><p>You can explore more event-specific services here:</p></div><nav class="moment-links" aria-label="Event-specific balloon services">
  <?php $moments=[['Baby shower balloons','baby-shower-balloons'],['Bridal shower balloons','bridal-shower-balloons'],['Corporate event balloons','corporate-event-balloons'],['Anniversary balloons','anniversary-balloons'],['Baptism balloons','baptism-balloons'],['Graduation balloons','graduation-balloons'],['Christmas balloons','christmas-balloons'],['Halloween balloons','halloween-balloons'],['Valentine’s Day balloons','valentines-day-balloons'],['Bar Mitzvah balloons','bar-mitzvah-balloons']]; foreach($moments as $moment): ?><a href="<?php echo esc_url(home_url('/services/'.$moment[1].'/')); ?>"><?php echo esc_html($moment[0]); ?><i class="fa-solid fa-arrow-right"></i></a><?php endforeach; ?>
  </nav><p class="about-note">Whatever you are celebrating, our team can help you choose balloon decor that fits your venue, colour palette, event style, and the atmosphere you want to create.</p></div></section>

  <section class="about-approach"><div class="hd-wrap about-split"><div class="about-copy"><h2>Our Approach</h2><p>We believe event decor should feel exciting, but the planning process should feel simple. When you contact us, we ask about your event type, date, location, colour palette, inspiration, and the kind of setup you have in mind. Then we help you choose the decor style that fits your celebration.</p><p>Our goal is to create balloon decoration that looks good in the room, works with the venue, and gives guests a beautiful place to take photos. Whether your event is small and minimal or bold and detailed, we focus on creating a polished setup that feels right for the occasion.</p></div><div class="approach-statement"><span>Thoughtful planning.</span><span>Clean installation.</span><span>Beautiful moments.</span></div></div></section>

</div>
<?php get_footer(); ?>
